TRAINED_MODEL = "craft_text_detection/weights/craft_mlt_25k.pth"
TEXT_THRESHOLD = 0.7
LOW_TEXT = 0.4
LINK_THRESHOLD = 0.4
CUDA = True
CANVAS_SIZE = 1280
MAG_RATIO = 1.5
POLY = False
SHOW_TIME = False
TEST_FORDEL = "/data/"
REFINE = False
REFINER_MODEL = "weights/craft_refiner_CTW1500.pth"
MODEL_PATH_CRNN = "crnn/data/crnn.pth"
ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz"
TESERACT_CONFIG = ('-l vie --oem 1 --psm 3')
PATH_FILE_FULL = "static/csv/full_drug_info.csv"
PATH_FILE_ELEMENT = "static/csv/drug_elements.csv"
